import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import ReactTypingEffect from 'react-typing-effect';

import { FaLinkedinIn, FaGithub } from 'react-icons/fa';

const SUBTITLE_TEXTS = ['Software Enginner', 'JS/TS Specialist', 'React Developer', 'Hacking the Gate :)']

const Home: NextPage = () => {
  const handleLinkedin = () => {
    window.open("https://www.linkedin.com/in/luisrondow/");
  };

  const handleGithub = () => {
    window.open("https://github.com/luisrondow");
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Luis Rondow - Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.avatar}></div>
        <div className={styles.title}>
          <h1>Luis Rondow</h1>
          <ReactTypingEffect text={SUBTITLE_TEXTS} speed={100} eraseSpeed={100}  eraseDelay={2500} />
        </div>

        <div className={styles.icons}>
          <FaLinkedinIn className={styles.icon} onClick={handleLinkedin} />
          <FaGithub className={styles.icon} onClick={handleGithub} />
        </div>
      </main>
    </div>
  )
}

export default Home
